version: "3"
services:
  db:
    image: postgres:latest
    container_name: green_assets-postgres-db
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: user
      POSTGRES_USER: user
      POSTGRES_DB: green_assets

  adminer:
    image: adminer
    container_name: green_assets-adminer
    restart: always
    ports:
      - "2080:8080"
